<a href="https://colab.research.google.com/github/prathameshp24/PyTorch_tutorials/blob/main/PyTorch_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors in PyTorch - A detailed guide

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
## Check if GPU is available or not

if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")

else:
    print("GPU is not available")
    device = torch.device("cpu")

GPU is available


## Creating a Tensor

In [4]:
# Using empty

arr = torch.empty(2,3)
print(arr)                                ## initializes an empty tensor with provided shape. Assigns garbage values.

tensor([[0.0079, 0.0000, 0.0086],
        [0.0000, 0.0000, 0.0000]])


In [6]:
# Check Type

type(arr)

torch.Tensor

In [7]:
# Using Zeros

arr = torch.zeros(2,3)
print(arr)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
print(arr.dtype)

torch.float32


In [9]:
# Using ones
arr = torch.ones(2,3)
print(arr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
# Using random

arr = torch.rand(2,3)
print(arr)

tensor([[0.4281, 0.9224, 0.2037],
        [0.4461, 0.3816, 0.4738]])


In [11]:
# Using seed (repetitive random values)

arr = torch.manual_seed(42)
arr = torch.rand(2,3)
print(arr)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [12]:
# Using tensors

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# Other ways

# arange
print("With arange : ", torch.arange(0,10))

# linspace
print("with linspace : ", torch.linspace(0, 10, 2))

# using eye
print("with eye : ", torch.eye(5))

# using full
print("with full : ", torch.full((3,3),5))

With arange :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
with linspace :  tensor([ 0., 10.])
with eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
with full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
# Copying a shape of any tensor to other

y = torch.empty_like(x)
y.shape

torch.Size([2, 3])

In [18]:
y = torch.zeros_like(x)
y.shape

torch.Size([2, 3])

In [19]:
y = torch.ones_like(x)
y.shape

torch.Size([2, 3])

In [29]:
## Important : torch.rand_like(x) will not work because of conflicting datatypes.

y = torch.rand_like(x,dtype = torch.float32)
y.shape


torch.Size([2, 3])

## Tensor Datatypes

In [22]:
# Finding a datatype

x = torch.tensor([[1,2,3],[4,5,6]])
x.dtype

torch.int64

In [23]:
# Assigning a datatype

x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(x)
print(x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [26]:
# x = torch.tensor("abc", dtype=torch.int64)
# print(x)
# print(x.dtype)
# Cannot directly put strings in tensors. However, we can store embeddings

In [27]:
# using to()

x = x.to(torch.int64)
print(x)
print(x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


# Mathematical Operations on Tensors

## Scalar Operations

In [30]:
x = torch.rand(2,2)
print(x)

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])


In [31]:
# addition
x + 2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [32]:
# subtraction
x - 2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [33]:
# multiplication
x * 2

tensor([[1.7388, 1.1354],
        [1.4822, 0.8588]])

In [34]:
# division
x/ 2

tensor([[0.4347, 0.2839],
        [0.3705, 0.2147]])

In [35]:
# int division
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [36]:
# modulo
x % 2

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [37]:
# power
x ** 2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

## Element wise operations

In [38]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [39]:
# addition
x + y

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

In [40]:
# subtraction
x - y

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

In [42]:
# multiplication , elementwise by default
x * y

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

In [43]:
# division
x / y

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

In [44]:
# int division
x // y

tensor([[2., 0., 2.],
        [2., 0., 2.]])

In [45]:
# power
x ** y

tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])

In [46]:
# modulo
x % y

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [47]:
z = torch.tensor([1, -2, 3, -4])

In [48]:
# abs
torch.abs(z)

tensor([1, 2, 3, 4])

In [49]:
# negative
torch.neg(z)

tensor([-1,  2, -3,  4])

In [51]:
d = torch.tensor([1.2, 2.3, 3.4, 4.5])

In [52]:
# round
torch.round(d)

tensor([1., 2., 3., 4.])

In [53]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [54]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [56]:
# clamp
torch.clamp(d, min = 1.5, max = 2.5)

tensor([1.5000, 2.3000, 2.5000, 2.5000])

## Reduction Operation

In [57]:
e = torch.randint(size=(2,3), low=0, high=10)
print(e)

tensor([[7, 9, 2],
        [0, 5, 9]])


In [58]:
# sum
torch.sum(e)

tensor(32)

In [59]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 7, 14, 11])

In [60]:
# sum along rows
torch.sum(e, dim=1)

tensor([18, 14])

In [63]:
# mean
torch.mean(e, dtype=torch.float32)

tensor(5.3333)

In [64]:
# mean along columns
torch.mean(e, dim=0, dtype=torch.float32)

tensor([3.5000, 7.0000, 5.5000])

In [65]:
# mean along rows
torch.mean(e, dim=1, dtype=torch.float32)

tensor([6.0000, 4.6667])

In [66]:
# median
torch.median(e)

tensor(5)

In [67]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9)
tensor(0)


In [68]:
# product
torch.prod(e)

tensor(0)

In [73]:
# standard deviation
torch.std(e.to(torch.float32))

tensor(3.7238)

In [74]:
# variance
torch.var(e.to(torch.float32))

tensor(13.8667)

In [75]:
# argmax
torch.argmax(e)

tensor(1)

In [76]:
# argmin
torch.argmin(e)

tensor(3)

## Matrix operations

In [77]:
a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(3,2), low=0, high=10)

print(a)
print(b)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [78]:
# Matrix multiplication
torch.matmul(a,b)

tensor([[109,  69],
        [ 50,  30]])

In [79]:
# Dot product
vecA = torch.tensor([1,2])
vecB = torch.tensor([3,4])

torch.dot(vecA, vecB)


tensor(11)

In [82]:
# Transpose
print(torch.transpose(a, 0, 1))

tensor([[3, 6],
        [4, 2],
        [9, 0]])


In [83]:
h = torch.randint(size=(3,3), low=0, high=10)
print(h)

tensor([[3, 4, 3],
        [7, 0, 9],
        [0, 9, 6]])


In [87]:
# determinant
torch.det(h.to(dtype=torch.float32))

tensor(-222.)

In [88]:
# inverse
torch.inverse(h.to(dtype=torch.float32))

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

## Comparison OPerations

In [89]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [90]:
# greater than
print(i > j)

tensor([[True, True, True],
        [True, True, True]])


In [91]:
# less than
print(i < j)

tensor([[False, False, False],
        [False, False, False]])


In [93]:
# greater than or equalto
print(i >= j)                       ## Similar for less than or equal to

tensor([[True, True, True],
        [True, True, True]])


In [94]:
# equal to
print(i == j)

tensor([[False, False, False],
        [False, False, False]])


In [95]:
# not equal to
print(i != j)

tensor([[True, True, True],
        [True, True, True]])


## Special Operations

In [96]:
k = torch.randint(size=(2,3), low=0, high=10)
print(k)

tensor([[0, 1, 1],
        [7, 9, 4]])


In [97]:
# log
torch.log(k.to(dtype=torch.float32))

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [98]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [99]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [100]:
# sigmoid
torch.sigmoid(k.to(dtype=torch.float32))

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [101]:
# softmax
torch.softmax(k.to(dtype=torch.float32), dim=0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

In [102]:
# relu
torch.relu(k)

tensor([[0, 1, 1],
        [7, 9, 4]])

## Inplace Operations

In [103]:
m = torch.randint(size=(2,3), low=0, high=10)
n = torch.randint(size=(2,3), low=0, high=10)
print(m)
print(n)

tensor([[3, 8, 9],
        [3, 7, 8]])
tensor([[1, 4, 1],
        [6, 3, 2]])


In [104]:
m += n

In [105]:
print(m)

tensor([[ 4, 12, 10],
        [ 9, 10, 10]])


In [106]:
m -= n
print(m)

tensor([[3, 8, 9],
        [3, 7, 8]])


In [107]:
m.add_(n)
print(m)

tensor([[ 4, 12, 10],
        [ 9, 10, 10]])


In [108]:
m.subtract_(n)
print(m)

tensor([[3, 8, 9],
        [3, 7, 8]])


In [109]:
m.relu_()

tensor([[3, 8, 9],
        [3, 7, 8]])

## Copy one tensor into another

In [111]:
## Why not assignment operator??

a = torch.randint(size=(2,3), low=0, high=10)
b = a

print(b)

a[0][0] = 1
print(b)                ## We do not want change. Then what?

tensor([[7, 5, 9],
        [1, 5, 1]])
tensor([[1, 5, 9],
        [1, 5, 1]])


In [112]:
b = a.clone()
a[0][0] = 9
print(b)

tensor([[1, 5, 9],
        [1, 5, 1]])


# Tensor Operations on GPU

In [113]:
torch.cuda.is_available()

True

In [114]:
device = torch.device("cuda")

In [115]:
# creating a tensor on GPU
a = torch.rand(size=(2,3), device=device)
print(a)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')


In [116]:
# moving a tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])

In [117]:
a.to(device)

tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]], device='cuda:0')

## What difference does this make?

In [118]:
import time

# define the size of matrices
size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# matrix multiplication on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
cpu_time = end_time - start_time

# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# matrix multiplication on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
end_time = time.time()
gpu_time = end_time - start_time


# print values
print("CPU time: ", cpu_time)
print("GPU time: ", gpu_time)
print("Speedup: ", cpu_time/gpu_time)

CPU time:  26.11034345626831
GPU time:  0.7043485641479492
Speedup:  37.07020186497293


## Reshaping Tensors

In [119]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [121]:
# reshape
a.reshape(4,1,1,4)

tensor([[[[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]]]])

In [124]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
b = torch.rand(2,3,4)
b

tensor([[[0.2821, 0.1318, 0.0690, 0.5509],
         [0.0119, 0.3645, 0.5644, 0.8473],
         [0.0240, 0.7587, 0.4538, 0.8144]],

        [[0.2974, 0.5387, 0.8459, 0.9872],
         [0.5965, 0.5405, 0.7924, 0.5388],
         [0.2656, 0.8488, 0.5751, 0.5396]]])

In [127]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [129]:
# unsqueeze (adds dimension at specified location)
a = torch.rand(226,226,3)
a.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [130]:
# squeeze (removes dimension)
a.unsqueeze(0).squeeze(0).shape

torch.Size([226, 226, 3])

## Numpy and PyTorch

In [131]:
import numpy as np

In [132]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [133]:
b = a.numpy()
b

array([1, 2, 3])

In [134]:
type(b)

numpy.ndarray

In [135]:
a = torch.from_numpy(b)
type(a)

torch.Tensor